# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99e7ebd584560c93a532955586528efa4583de3f0eeb9dfecba8ab07356b28a4e4186cfd75353e1b62adb6fa181f100ed47ad1d3491d5518b21135c48309bd56

test:
  secret_key_base: 7e6912e9a9cd28f68ffb5ab347720b8c767516a0f25f3bbbf87ddc32c7c6cf4aaa59679c14954b94d7011d3d6eeaa28afc0196e4f8e257f6ebb6743c4cae2e4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
